#!/bin/bash
# install service in dev container

cd /workspace

# upgrade pip
python -m pip install --upgrade pip


# install or upgrade dependencies for development and testing
pip install --upgrade -r requirements-dev.txt

# install the package itself in edit mode:
pip install -e .

# install pre-commit hooks to git
pre-commit install
