# This file is only needed, if your repository uses FastAPI
name: Check if openapi.yaml is up to date

on: push

jobs:
  static-code-analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - id: common
        uses: ghga-de/gh-action-common@v2

      - name: Check if openapi.yaml is up to date
        run: |
          export ${{ steps.common.outputs.CONFIG_YAML_ENV_VAR_NAME }}="${{ steps.common.outputs.CONFIG_YAML }}"

          ./scripts/update_openapi_docs.py --check
