name: Check template files

on: push

jobs:
  check-template-files:
    name: Check template files

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        id: checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        id: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Check template files
        id: check-template-files
        run: |
          if [ "${{ github.event.repository.name }}" == "microservice-repository-template" ]
          then
            echo "Skipping this test as operating on the template repo."
          else
            ./scripts/update_template_files.py --check
          fi
