name: Check template files

on: push

jobs:
  check-template-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Check template files
        run: |
          if [ "${{ github.event.repository.name }}" == "microservice-repository-template" ]
          then
            echo "Skipping this test as operating on the template repo."
          else
            ./scripts/update_template_files.py --check
          fi
