name: Check if pyproject.toml file is up to date

on: push

jobs:
  static-code-analysis:
    name: Check pyproject file

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        id: checkout
        uses: actions/checkout@v5

      - name: Common steps
        id: common
        uses: ghga-de/gh-action-common@v6
        with:
          python-version: '3.13'

      - name: Check pyproject.toml
        id: check-pyproject
        run: |
          ./scripts/update_pyproject.py --check
